#camunda.bpm.admin-user:
#  id: admin
#  password: admin
camunda:
  bpm:
    generic-properties:
      properties:
        historyTimeToLive: P36500D
vider:
  atom:
    schema: vider_preprod
  external:
    required:
      automation: false

server:
  servlet:
    context-path: /
spring.main.allow-bean-definition-overriding: true

spring:
  datasource:
    primary:
      url: jdbc:mysql://vider-db.ctnm6mdla58b.ap-south-1.rds.amazonaws.com:3306/camunda?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      username: admin
      driver-class-name: com.mysql.cj.jdbc.Driver
    secondary:
      url: jdbc:mysql://vider-db.ctnm6mdla58b.ap-south-1.rds.amazonaws.com:3306/vider_preprod?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      username: admin
      driver-class-name: com.mysql.cj.jdbc.Driver
logging:
  pattern:
    console: '{"t": "%d{yyyy-MM-ddTHH:mm:ss.SSSZ}", "CorrelationId": "%X{CorrelationId}", "Module": "%logger{35}", "Message": "%msg", "level": "%-5level"} %n'

